### ISSUE TITLE
Авторство идеи

### ISSUE THREAD

**Issue by roose** [mihdan/mihdan-hate-everything-stickers#16]
Эй я вообще-то давно их сделал,https://twitter.com/mr_roose/status/961851679497842690 могли бы и упомянуть, так-то они не под открытой лицензией

**Comment by DimaMinka** [comment]
Согласен, идея отличная! Спасибо за нее, но у нас довольно нишевые стикеры, все разработано с нуля... Credits добавим без проблем, нам не жалко, а про лицензию вообще не понял, она при чем? Эту идею не мы первые юзаем, не мы последние... В любом случае благодарность нашу примите, readme поправим... И конечно же...
**Авторство ГОВНО** 🤪

**Comment by mihdan** [comment]
@roose оргинальная идея, коллега, конечно, принадлежит вам, бесспорно. Добавим в описание. 
Мы добавили стикеры, которых нет у вас в наборе.
