### ISSUE TITLE
Предложение по поводу шрифта.

### ISSUE THREAD

**Issue by pavlo-bondarchuk** [mihdan/mihdan-hate-everything-stickers#26]
Прошу прощения, воспользуюсь наглостью, но все-таки предложу перейти на гугл-шрифт. 
В наборе сейчас используется шрифт _avenir next bold_ чтобы избавиться от проблем с лицензированием - лучше перейти на бесплатный вариант гугл-шрифта. [Посмотрев](https://fontsup.com/similar/avenir-next-lt-pro.html) и сравнив шрифты  - остановился на Noto Sans начертание Condensed Bold как наиболее подходящий и кириллический. Вот [ссылка](https://www.figma.com/file/i3VeHFoIQi4hD2QTjBxSeb/mihdan-hate-everything-stickers?node-id=0%3A1) на проект в Figma.

**Comment by DimaMinka** [comment]
я не против. 
@mihdan что скажешь?

**Comment by mihdan** [comment]
Норм, я не против

**Comment by pavlo-bondarchuk** [comment]
Всем спасибо! Я закрою этот issue.
